# config/schema/commerce_norelavon.schema.yml
commerce_payment.commerce_payment_gateway.plugin.elavon_redirect_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    accountid:
      type: string
      label: 'Account ID'
    userid:
      type: string
      label: 'User ID'
    pin:
      type: string
      label: 'PIN'
    pin_ca:
      type: string
      label: 'PIN CA'