<?php

/**
 * Convenience function to get Norgen zones.
 *
 * This function retrieves Norgen zones for commerce shipping.
 *
 * @return array An array containing Norgen zone types (e.g., 'US', 'CA').
 */

function commerce_norshipping_zone_types()
{
    return array(
        'US',
        'CA',
        'NAA',
        'NAB',
        'NAC',
        'EUW',
        'EUE',
        'ASA',
        'ASB',
        'ASC',
        'ASD',
        'ASE',
        'ASF',
        'ASG',
        'SAA',
        'SAB',
        'AU',
    );
}