<?php

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Database\Database;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;

//to give managers access
use Drupal\user\Entity\Role;

// function nor_abandoned_cart_report_preprocess_node(&$variables) {
//   if ($variables['node']->id() == '2570') {
//     $current_user = \Drupal::currentUser();
//     if (!($current_user->hasRole('administrator') || $current_user->hasRole('manager'))) {
//       $request = \Drupal::request();
//       $referer = $request->headers->get('referer');
//       $redirect_url = $referer ? $referer : Url::fromRoute('<front>')->toString();
//       $response = new TrustedRedirectResponse($redirect_url);
//       $response->send();
//       exit();
//     }
//   }
// }

/**
 * Implements hook_install().
 */
function nor_abandoned_cart_report_install() {
  // Load the "manager" role.
  $role = Role::load('manager');
  if ($role) {
    // Grant the 'access manager reports' permission to the "manager" role.
    $role->grantPermission('access manager reports');
    $role->save();
  }
}
